services:
  api:
    build: .
    container_name: user-service-api
    profiles: ["app"]
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - cqrs-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    profiles: ["infra"]
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - cqrs-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    profiles: ["infra"]
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: write_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d write_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cqrs-network

  mongodb:
    image: mongo:7.0-jammy
    container_name: mongodb
    profiles: ["infra"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cqrs-network
volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  cqrs-network:
    driver: bridge
